"""add_names_to_user_account

Revision ID: 801696397704
Revises: 69aff58178ff
Create Date: 2026-03-01 23:34:26.348868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801696397704'
down_revision: Union[str, Sequence[str], None] = '69aff58178ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('first_name', sa.String(length=32), nullable=True))
    op.add_column('user_account', sa.Column('last_name', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'last_name')
    op.drop_column('user_account', 'first_name')
    # ### end Alembic commands ###
